services:
  backend-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: clientes_finanzas_tests
    volumes:
      - maven_repo:/root/.m2
      - ./target/surefire-reports:/app/target/surefire-reports

volumes:
  maven_repo:
